version: "2"

run:
  timeout: 5m

linters:
  exclusions:
    paths:
      - ^docs/external/jotform-api-go/.*\.go$
    rules:
      - path: ^docs/external/jotform-api-go/.*\.go$
        linters:
          - errcheck
